//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Food_Ordering_System.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Food_Ordering_System.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Adam_Liaw {
            get {
                object obj = ResourceManager.GetObject("Adam Liaw", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AMA_Sushi_Menu___Food_Photography {
            get {
                object obj = ResourceManager.GetObject("AMA Sushi Menu _ Food Photography", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Browse_thousands_of_Button_3D_Animation_images_for_design_inspiration {
            get {
                object obj = ResourceManager.GetObject("Browse thousands of Button 3D Animation images for design inspiration", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Browse_thousands_of_Button_3D_Animation_images_for_design_inspiration1 {
            get {
                object obj = ResourceManager.GetObject("Browse thousands of Button 3D Animation images for design inspiration1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Browse_thousands_of_Button_3D_Animation_images_for_design_inspiration2 {
            get {
                object obj = ResourceManager.GetObject("Browse thousands of Button 3D Animation images for design inspiration2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Browse_thousands_of_Button_3D_Animation_images_for_design_inspiration3 {
            get {
                object obj = ResourceManager.GetObject("Browse thousands of Button 3D Animation images for design inspiration3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Buttons_stock_illustration__Illustration_of_periodic__dimensions___2821609 {
            get {
                object obj = ResourceManager.GetObject("Buttons stock illustration_ Illustration of periodic, dimensions - 2821609", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap contacts_icon {
            get {
                object obj = ResourceManager.GetObject("contacts icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Contacts_White_Icon {
            get {
                object obj = ResourceManager.GetObject("Contacts White Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download {
            get {
                object obj = ResourceManager.GetObject("download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download__1_ {
            get {
                object obj = ResourceManager.GetObject("download (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download__2_ {
            get {
                object obj = ResourceManager.GetObject("download (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download__2_1 {
            get {
                object obj = ResourceManager.GetObject("download (2)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Entry_And_Exit_Gate_Sign_Board_Pack_of_1_Entry_1_Exit_Board____Petro_Mart {
            get {
                object obj = ResourceManager.GetObject("Entry And Exit Gate Sign Board(Pack of 1 Entry 1 Exit Board) - Petro Mart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Exit_Button_stock_vector__Illustration_of_leaving__away___2232939 {
            get {
                object obj = ResourceManager.GetObject("Exit Button stock vector_ Illustration of leaving, away - 2232939", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Exit_Button_stock_vector__Illustration_of_leaving__away___22329391 {
            get {
                object obj = ResourceManager.GetObject("Exit Button stock vector_ Illustration of leaving, away - 22329391", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Exit_Button_stock_vector__Illustration_of_leaving__away___22329392 {
            get {
                object obj = ResourceManager.GetObject("Exit Button stock vector_ Illustration of leaving, away - 22329392", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Iconos_de_Flecha_Izquierda_para_descargar_gratis {
            get {
                object obj = ResourceManager.GetObject("Iconos de Flecha Izquierda para descargar gratis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Iconos_gratuitos_de_Flecha_Izquierda_diseñados_por_Lizel_Arina {
            get {
                object obj = ResourceManager.GetObject("Iconos gratuitos de Flecha Izquierda diseñados por Lizel Arina", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mensaje_General___MiLiberty {
            get {
                object obj = ResourceManager.GetObject("Mensaje General - MiLiberty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Morrisons___Food_To_Order {
            get {
                object obj = ResourceManager.GetObject("Morrisons - Food To Order", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Next_Button_Clipart_Transparent_PNG_Hd__Game_Button_Next_Button__Game__Button__Switch_PNG_Image_For_Free_Download {
            get {
                object obj = ResourceManager.GetObject("Next Button Clipart Transparent PNG Hd, Game Button Next Button, Game, Button, Sw" +
                        "itch PNG Image For Free Download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Philippine_Peso_free_vector_icons_designed_by_iconixar {
            get {
                object obj = ResourceManager.GetObject("Philippine Peso free vector icons designed by iconixar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Philippine_peso_free_vector_icons_designed_by_iconixar__1_ {
            get {
                object obj = ResourceManager.GetObject("Philippine peso free vector icons designed by iconixar (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Philippines_Peso_Currency_Symbol_free_icons_designed_by_Freepik {
            get {
                object obj = ResourceManager.GetObject("Philippines Peso Currency Symbol free icons designed by Freepik", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Premium_Vector___Japanese_food {
            get {
                object obj = ResourceManager.GetObject("Premium Vector _ Japanese food", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Premium_Vector___Japanese_food1 {
            get {
                object obj = ResourceManager.GetObject("Premium Vector _ Japanese food1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Profile_Icon_Silhouette_PNG_Transparent__Avatar_Icon_Profile_Icon_Member_Login_Vector_Isolated__Login_Icons__Profile_Icons__Avatar_Icons_PNG_Image_For_Free_Download {
            get {
                object obj = ResourceManager.GetObject("Profile Icon Silhouette PNG Transparent, Avatar Icon Profile Icon Member Login Ve" +
                        "ctor Isolated, Login Icons, Profile Icons, Avatar Icons PNG Image For Free Downl" +
                        "oad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Retro_Japanese_Ramen_Icon_by_meatman {
            get {
                object obj = ResourceManager.GetObject("Retro Japanese Ramen Icon by meatman", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Salmon_Fish_and_Product_Icon_Set_Stock_Vector___Illustration_of_gold__coin__127540410 {
            get {
                object obj = ResourceManager.GetObject("Salmon Fish and Product Icon Set Stock Vector - Illustration of gold, coin_ 12754" +
                        "0410", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Shabu_Shabu_in_Wien {
            get {
                object obj = ResourceManager.GetObject("Shabu Shabu in Wien", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Shoyu_Ramen {
            get {
                object obj = ResourceManager.GetObject("Shoyu Ramen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Shoyu_Ramen1 {
            get {
                object obj = ResourceManager.GetObject("Shoyu Ramen1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Takoyaki {
            get {
                object obj = ResourceManager.GetObject("Takoyaki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Yakisoba_noodles_prato_de_yakisoba_com_carne_de_frango_e_vegetais___Foto_Premium {
            get {
                object obj = ResourceManager.GetObject("Yakisoba noodles prato de yakisoba com carne de frango e vegetais _ Foto Premium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Yakitori_Recipe_焼き鳥 {
            get {
                object obj = ResourceManager.GetObject("Yakitori Recipe 焼き鳥", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
